name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: deploy
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm install

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
