name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: deploy
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: npm run deploy
